# Numpy Tutorial
(from freeCodeCamp.org; [link to youtube](https://www.youtube.com/watch?v=QUT1VHiLmmI))

In [3]:
import numpy as npprint( y[:] )

initialize an array:

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [13]:
b = np.array([[9.0,8.0,7.0], [6.0, 5.0, 4.0]])
print(b)

# has a casting hierarchy it uses apparently
# auto-converting the ints ~~> floats
b_2 = np.array([[9,8,7], [6, 5, 4.0]])
print(b_2)

[[9. 8. 7.]
 [6. 5. 4.]]
[[9. 8. 7.]
 [6. 5. 4.]]


In [12]:
# length mis-match -- doesn't make a hyper-cube
b_corrupt = np.array([[9.0,8.0,7.0], [6.0, 5.0]])
print(b_corrupt)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [19]:
print(a.shape)
print(b.shape)
print(b_2.shape)
print()
print(a.ndim)
print(b.ndim)
print(b_2.ndim)
print()
print(a.dtype)
print(b.dtype)
print(b_2.dtype)

(3,)
(2, 3)
(2, 3)

1
2
2

int64
float64
float64


In [25]:
a = np.array([1,2,3,4,5,6], dtype='int16')
print(a)
print(a.dtype)
print(a.itemsize)
print(a.size)

[1 2 3 4 5 6]
int16
2
6


# --------------

In [60]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a[0,3])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
4


In [61]:
# row 0
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [62]:
# col 0
a[:,0]

array([1, 8])

In [63]:
# get row 0 2nd through 5th element
a[0,1:5]

array([2, 3, 4, 5])

In [64]:
# change individual values
a[1,0] = 2000
a

array([[   1,    2,    3,    4,    5,    6,    7],
       [2000,    9,   10,   11,   12,   13,   14]])

In [65]:
# change multiple values
a[:, 3:8]=12
print(a)

[[   1    2    3   12   12   12   12]
 [2000    9   10   12   12   12   12]]


In [66]:
# ¿¡ this I don't understand !?
a[:, 2:-1]=0
print(a)

[[   1    2    0    0    0    0   12]
 [2000    9    0    0    0    0   12]]


In [72]:
# 3D example
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)
print()

# order of referents matches order brackets from leftmost to right most and outer to inner
print(d[:,0,1])
print(d[0,:,1])
print(d[0,1,:])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[2 6]
[2 4]
[3 4]


In [73]:
# testing above let,s get '5'
d[1,0,0]

5

# Initializing different types of arrays

In [75]:
# zeroes matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [81]:
np.zeros((1,1,1))

array([[[0.]]])

In [83]:
np.zeros((0,0,0,0,3))

array([], shape=(0, 0, 0, 0, 3), dtype=float64)

In [88]:
# ones matrix
np.ones((2,3,4), dtype='int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [91]:
# specified-num matrix
np.full((1,1,1,2,3),66, dtype='float64')

array([[[[[66., 66., 66.],
          [66., 66., 66.]]]]])

In [95]:
# copy shape, init with specified number
print(a.shape)
a_like = np.full_like(a, 8)
print(a_like)
print(a_like.shape)
print()

# Take shape, init with specified number
print(a.shape)
a_like = np.full(a.shape, 8)
print(a_like)
print(a_like.shape)

(2, 7)
[[8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]]
(2, 7)

(2, 7)
[[8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]]
(2, 7)


In [105]:
# random values
# ¡ different syntax; takes values rather than tuple !
np.random.rand(2,4,3)

array([[[0.34954456, 0.12423374, 0.46160577],
        [0.12652188, 0.84613502, 0.9393426 ],
        [0.2274044 , 0.98971685, 0.4665128 ],
        [0.21637389, 0.20759699, 0.27832833]],

       [[0.11761272, 0.03655905, 0.91527947],
        [0.79067062, 0.9653749 , 0.68567736],
        [0.26889991, 0.81513482, 0.45842908],
        [0.0651226 , 0.85938647, 0.45899107]]])

In [106]:
# take in a given shape
np.random.random_sample(b.shape)

array([[0.17575445, 0.10569936, 0.57113455],
       [0.09416977, 0.33643764, 0.57180023]])

In [111]:
# specify type
# ¡ again, different syntax !
# ¡¡ also, now the lower digit is invluded and higher is excluded for value range !!
np.random.randint(0,2, size=(3,4,5))

array([[[0, 1, 1, 0, 1],
        [1, 0, 1, 0, 0],
        [1, 0, 1, 1, 1],
        [0, 0, 0, 0, 1]],

       [[1, 1, 1, 0, 1],
        [0, 0, 0, 1, 1],
        [1, 1, 1, 1, 0],
        [0, 1, 0, 1, 1]],

       [[1, 1, 0, 0, 1],
        [1, 0, 1, 0, 0],
        [1, 1, 0, 0, 0],
        [0, 0, 0, 1, 0]]])

In [116]:
# identity matrix (2D)
np.identity(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [123]:
# repeats an array n times, 
# if the array can hold it (by dint of having specified dims beforehand)

arr = np.array([[1,2,3]])
print(arr)
print()
r0 = np.repeat(arr, 3, axis=0)
print(r0)
print()
r1 = np.repeat(arr, 3, axis=1)
print(r1)


[[1 2 3]]

[[1 2 3]
 [1 2 3]
 [1 2 3]]

[[1 1 1 2 2 2 3 3 3]]


In [143]:
# making a funky array (per video's request)
funk_arr = np.zeros((5,5), dtype='int8')
funk_arr[0,:] = 1
funk_arr[4,:] = 1
funk_arr[:,0] = 1
funk_arr[:,4] = 1
funk_arr[2,2] = 9

funk_arr_2 = np.ones((5,5), dtype='int8')
funk_arr_2[1:4,1:4] = 0
funk_arr_2[2,2] = 9

print(funk_arr)
print()
print(funk_arr_2)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [151]:
# given solution (notable becuase we're assigning a matrix)
ones_arr = np.ones((5,5))
zeros_arr = np.zeros((3,3))
zeros_arr[1,1] = 9
ones_arr[1:-1,1:-1] = zeros_arr  
# note that for a more varied matrix being assinged this would be much easier

print(ones_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays!!!

In [155]:
# array copies (via assignment) are pointers it appears
a = np.array([1,2,3])
print(f"a: {a}")

b = a
print(f"b: {b}")

a[0] = 111111
print(f"a: {a}")
print(f"b: {b}")

a: [1 2 3]
b: [1 2 3]
a: [111111      2      3]
b: [111111      2      3]


In [157]:
# we can assign to a `_.copy()` to get aroudn this
a = np.array([1,2,3])
print(f"a: {a}")

b = a.copy()
print(f"b: {b}")

a[0] = 111111
print(f"a: {a}")
print(f"b: {b}")

a: [1 2 3]
b: [1 2 3]
a: [111111      2      3]
b: [1 2 3]


# Mathematics

In [173]:
a = np.array([0,1,2,3])
print(f"a  : {a}")

print(f"a+1: {a+1}")
print(f"a/2: {a/2}")
print(f"a+a: {a+a}")
print(f"a**2: {a**2}")

a  : [0 1 2 3]
a+1: [1 2 3 4]
a/2: [0.  0.5 1.  1.5]
a+a: [0 2 4 6]
a**2: [0 1 4 9]


In [174]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

## Linear Algebra

In [181]:
a = np.ones((2,3))
print(f"a:\n{a}")
print()

b = np.full((3,2),2)
print(f"b:\n{b}")

np.matmul(a,b)

a:
[[1. 1. 1.]
 [1. 1. 1.]]

b:
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [182]:
a @ b

array([[6., 6.],
       [6., 6.]])

In [183]:
c = np.identity(3)
np.linalg.det(c)

1.0

# Stats

In [184]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [185]:
np.min(stats)

1

In [187]:
np.max(stats[:,1])

5

In [189]:
np.max(stats, axis=1)

array([4, 5, 6])

In [197]:
# interestingly gives max for each tensor connected to that axis element
stats_2 = np.array([[1,2,3],[3,2,1]])
print(stats_2)
np.max(stats_2, axis=0)

[[1 2 3]
 [3 2 1]]


array([3, 2, 3])

In [198]:
np.sum(stats_2)

12

# Reorganizing Arrays

In [213]:
before = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(f"before:\n{before}")
print(f"before.shape: {before.shape}")
print(f"before.size: {before.size}")

before:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
before.shape: (2, 8)
before.size: 16


In [214]:
after = before.reshape((4,4))
print(f"after:\n{after}")
print(f"after.shape: {after.shape}")
print(f"after.size: {after.size}")

after:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
after.shape: (4, 4)
after.size: 16


In [218]:
# Vertically stacking vectors
r1 = np.array([1,2,3,4,5])
r2 = r1+5
print(r1)
print(r2)
print()

np.vstack([r1,r2,r2,r1])


[1 2 3 4 5]
[ 6  7  8  9 10]



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [219]:
np.hstack([r1,r2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Miscellaneous

### Load Data from File

In [225]:
# Note: the path seems 
# to default to the dir of the jupyter file
filedata = np.genfromtxt('data_to_load.txt', delimiter=',')
filedata

array([[1.0000e+00, 1.3000e+01, 2.1000e+01, 1.1000e+01, 1.9600e+02],
       [2.0000e+00, 4.0000e+00, 5.3000e+01, 4.2000e+01, 4.2330e+03],
       [3.2432e+04, 2.3100e+02, 1.0000e+00, 2.3000e+01, 4.3200e+02]])

In [230]:
# a type casting option
# ¡ Note: this does not auto-replace the orig !
print(filedata.astype('int16'))
print()
print(filedata)

[[    1    13    21    11   196]
 [    2     4    53    42  4233]
 [32432   231     1    23   432]]

[[1.0000e+00 1.3000e+01 2.1000e+01 1.1000e+01 1.9600e+02]
 [2.0000e+00 4.0000e+00 5.3000e+01 4.2000e+01 4.2330e+03]
 [3.2432e+04 2.3100e+02 1.0000e+00 2.3000e+01 4.3200e+02]]


### Boolean Masking and Advanced indexing

In [231]:
filedata > 50

array([[False, False, False, False,  True],
       [False, False,  True, False,  True],
       [ True,  True, False, False,  True]])

In [233]:
# indexing with booleans
filedata[filedata > 50]

array([  196.,    53.,  4233., 32432.,   231.,   432.])

In [247]:
# indexing with a list
# hmm, doesn't seem to work nicely for non-1D
a = np.array([1,2,3,4,5,6])
a2 = a.reshape(2,3)
print(a)
print()
print(a2)
print()

a[[2,4,5]]

# will error out
# print()
#
# a2[[2,4,5]]

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]



array([3, 5, 6])

In [248]:
np.any(filedata > 50)

True

In [257]:
# any, with axis specification
np.any(filedata > 1000, axis=1)

array([False,  True,  True])

In [258]:
# all, with axis specification
np.all(filedata > 1000, axis=1)

array([False, False, False])

In [261]:
# `~` is "not" (which is a bit unfortunate)
~np.any(filedata > 1000, axis=1)

array([ True, False, False])

In [272]:
# assignment question

# first make matrix
block = np.array(list(range(1,31))).reshape(6,5)
print(f"block:\n{block}")
print()

# get mid section
print(f"section:\n{block[2:4, 0:2]}")

block:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

section:
[[11 12]
 [16 17]]


In [273]:
block[ [0,1,2,3],[1,2,3,4] ]

array([ 2,  8, 14, 20])

In [274]:
block[ [0],[1] ]

array([2])

In [275]:
block[ [0,4,5], 3: ]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

# Linear Alg (from elsewhere)

In [298]:
row_vector = np.array([[1,2,3]])
row_vector

array([[1, 2, 3]])

In [285]:
row_vector.shape

(1, 3)

In [286]:
column_vector = row_vector.reshape(-1,1)
column_vector

array([[1],
       [2],
       [3]])

In [287]:
column_vector.shape

(3, 1)

In [288]:
an_arr = np.array([1,2,3,4])
an_arr

array([1, 2, 3, 4])

In [289]:
an_arr[np.newaxis, :]

array([[1, 2, 3, 4]])

In [290]:
an_arr[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [291]:
an_arr[:, None]

array([[1],
       [2],
       [3],
       [4]])

In [293]:
matrix = np.array(list(range(1,7))).reshape(2,3)
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [296]:
# technically we're multiplying matrices here
np.matmul(matrix, column_vector)

array([[14],
       [32]])

In [315]:
# note that this is not the same as [[1,2,3]]
np.matmul(matrix, np.array([1,2,3]))

array([14, 32])

In [316]:
matrix @ column_vector

array([[14],
       [32]])

In [309]:
np.array([1,2,3]) @ np.array([1,2,3])

14

In [318]:
%timeit np.matmul(matrix, column_vector)

493 ns ± 4.89 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [319]:
%timeit matrix @ column_vector

487 ns ± 5.42 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [320]:
%timeit np.dot(matrix, column_vector)

480 ns ± 1.62 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [322]:
matrix.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [325]:
matrix.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [326]:
matrix @ matrix.T

array([[14, 32],
       [32, 77]])

In [327]:
matrix.T @ matrix

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

## Note: be sure to check out SciPy